# ============================================================
#  zsh 配置
# ============================================================

# ------------------------------------------------------------
#  0. 基础
# ------------------------------------------------------------
[[ -d "$HOME/.local/bin" ]] && case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) PATH="$HOME/.local/bin:$PATH" ;;
esac

# 关掉终端的 XOFF/XON 软件流控
[[ -t 0 ]] && stty -ixon 2>/dev/null

export ZSH="$HOME/.oh-my-zsh"

# ------------------------------------------------------------
#  1. 主题与插件
# ------------------------------------------------------------
ZSH_THEME="agnoster"

# fzf-tab 必须在 compinit 之后、但在会包裹 widget 的插件之前
plugins=()
plugins+=(git)

for _p in fzf-tab zsh-autosuggestions zsh-syntax-highlighting zsh-autopair; do
  if [[ -d "$ZSH/custom/plugins/$_p" || -d "$ZSH/plugins/$_p" ]]; then
    plugins+=("$_p")
  fi
done
unset _p

[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# ------------------------------------------------------------
#  2. 键位表
#
#  顺序必须是: 键位表 → 插件重新绑定 → 绑定自定义键
# ------------------------------------------------------------
bindkey -v
KEYTIMEOUT=1

# ------------------------------------------------------------
#  3. zsh-autopair
# ------------------------------------------------------------
if (( $+functions[autopair-init] )); then
  autopair-init
fi

# ------------------------------------------------------------
#  4. fzf
# ------------------------------------------------------------
if (( $+commands[fd] )); then
  _fd_bin=fd
elif (( $+commands[fdfind] )); then
  _fd_bin=fdfind
else
  _fd_bin=''
fi

if (( $+commands[bat] )); then
  _bat_bin=bat
elif (( $+commands[batcat] )); then
  _bat_bin=batcat
else
  _bat_bin=''
fi

if (( $+commands[fzf] )); then

  if [[ -n $_bat_bin ]]; then
    _fzf_preview="$_bat_bin --style=numbers --color=always --line-range :200 {} 2>/dev/null"
  else
    _fzf_preview='head -200 {} 2>/dev/null'
  fi

  _fzf_filegen() {
    if [[ -n $_fd_bin ]]; then
      $_fd_bin --type f --hidden --exclude .git
    else
      find . -type f -not -path '*/.git/*' 2>/dev/null
    fi
  }

  _fzf_dirgen() {
    if [[ -n $_fd_bin ]]; then
      $_fd_bin --type d --hidden --exclude .git
    else
      find . -type d -not -path '*/.git/*' 2>/dev/null
    fi
  }

  export FZF_DEFAULT_OPTS='--height 50% --reverse --border --bind=ctrl-e:down,ctrl-u:up'
  [[ -n $_fd_bin ]] && export FZF_DEFAULT_COMMAND="$_fd_bin --type f --hidden --exclude .git"

  # ---- ^R 历史命令 ----
  _fzf_history_widget() {
    local cmd
    cmd=$(fc -rl 1 2>/dev/null |
            sed -E 's/^[[:space:]]*[0-9]+[[:space:]]*//' |
            awk '!seen[$0]++' |
            fzf --tiebreak=index --bind='ctrl-r:toggle-sort' +m --query="$LBUFFER")
    local ret=$?
    if [[ -n $cmd ]]; then
      LBUFFER="$cmd"
      CURSOR=${#LBUFFER}
    fi
    zle reset-prompt
    return $ret
  }
  zle -N _fzf_history_widget

  # ---- ^T 跳到目录 ----
  _fzf_cd_widget() {
    local dir
    dir=$(_fzf_dirgen | fzf --preview 'ls -la {} 2>/dev/null' --preview-window 'right:50%' +m)
    local ret=$?
    if [[ -n $dir ]]; then
      BUFFER="cd ${(q)dir}"
      zle accept-line
      return 0
    fi
    zle reset-prompt
    return $ret
  }
  zle -N _fzf_cd_widget

  # ---- ^P 选文件并把路径插入命令行----
  _fzf_find_widget() {
    local files
    files=$(_fzf_filegen |
              fzf -m --preview "$_fzf_preview" --preview-window 'right:60%')
    local ret=$?
    if [[ -n $files ]]; then
      local -a sel
      sel=(${(f)files})
      LBUFFER+="${(j: :)${(q)sel}} "
      CURSOR=${#LBUFFER}
    fi
    zle reset-prompt
    return $ret
  }
  zle -N _fzf_find_widget

  # 显式指定键位表
  for _km in viins emacs; do
    bindkey -M $_km '^R' _fzf_history_widget
    bindkey -M $_km '^T' _fzf_cd_widget
    bindkey -M $_km '^P' _fzf_find_widget
  done
  unset _km

fi

# ------------------------------------------------------------
#  5. 命令耗时显示
# ------------------------------------------------------------
zmodload -F zsh/datetime b:strftime p:EPOCHREALTIME 2>/dev/null

_duration_preexec() {
  _cmd_start=$EPOCHREALTIME
}

_duration_precmd() {
  [[ -n ${_cmd_start:-} ]] || { RPS1=''; return }

  local d=$(( EPOCHREALTIME - _cmd_start ))
  unset _cmd_start

  if (( d >= 0.5 )); then
    if (( d >= 60 )); then
      printf -v RPS1 '%s%dm%.0fs%s' '%F{yellow}' $(( d / 60 )) $(( d % 60 )) '%f'
    else
      printf -v RPS1 '%s%.2fs%s' '%F{yellow}' "$d" '%f'
    fi
  else
    RPS1=''
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook preexec _duration_preexec
add-zsh-hook precmd  _duration_precmd

# ------------------------------------------------------------
#  6. vi-mode 光标形状
# ------------------------------------------------------------
zle-keymap-select() {
  if [[ ${KEYMAP} == vicmd ]] || [[ ${1:-} == 'block' ]]; then
    printf '\e[1 q'
  else
    printf '\e[5 q'
  fi
}
zle -N zle-keymap-select

_fix_cursor() { printf '\e[5 q' }
add-zsh-hook precmd _fix_cursor

# 启动即为插入模式的竖线
printf '\e[5 q'

# ------------------------------------------------------------
#  7. zoxide
# ------------------------------------------------------------
if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

# ------------------------------------------------------------
#  8. gr
# ------------------------------------------------------------
unalias gr 2>/dev/null

gr() {
  local root
  root=$(git rev-parse --show-toplevel 2>/dev/null) || {
    print -u2 "gr: 不在 git 仓库中"
    return 1
  }
  [[ -d $root ]] && builtin cd "$root"
}

# ------------------------------------------------------------
#  以下为可选组件，缺失时静默跳过
# ------------------------------------------------------------

# --- nvm ---
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"

# --- vcpkg ---
if [[ -z "${VCPKG_ROOT:-}" ]]; then
  for _d in "$HOME/vcpkg" "/opt/vcpkg" "/usr/local/vcpkg"; do
    [[ -d "$_d" ]] && { VCPKG_ROOT="$_d"; break; }
  done
  unset _d
fi
if [[ -n "${VCPKG_ROOT:-}" && -d "$VCPKG_ROOT" ]]; then
  export VCPKG_ROOT
  export VCPKG_FEATURE_FLAGS=-sslverify
  case ":$PATH:" in
    *":$VCPKG_ROOT:"*) ;;
    *) PATH="$VCPKG_ROOT:$PATH" ;;
  esac
fi
